/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomAttachmentCard: typeof import('./src/components/CustomAttachmentCard.vue')['default']
    CustomCourseCard: typeof import('./src/components/course/CustomCourseCard.vue')['default']
    CustomCourseStructureList: typeof import('./src/components/course/CustomCourseStructureList.vue')['default']
    CustomDeviceCard: typeof import('./src/components/CustomDeviceCard.vue')['default']
    CustomFloatBackButton: typeof import('./src/components/CustomFloatBackButton.vue')['default']
    CustomHorizontalCourseCard: typeof import('./src/components/CustomHorizontalCourseCard.vue')['default']
    CustomMessageCard: typeof import('./src/components/CustomMessageCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticEntryCard: typeof import('./src/components/personal/statistic/StatisticEntryCard.vue')['default']
    TheAccountBindCard: typeof import('./src/components/personal/info/TheAccountBindCard.vue')['default']
    TheAppInfoCard: typeof import('./src/components/personal/about/TheAppInfoCard.vue')['default']
    TheAvatarModifyCard: typeof import('./src/components/personal/info/TheAvatarModifyCard.vue')['default']
    TheCourseContentModifyCard: typeof import('./src/components/course/TheCourseContentModifyCard.vue')['default']
    TheCourseCountPieChart: typeof import('./src/components/statistics/TheCourseCountPieChart.vue')['default']
    TheCourseCreationForm: typeof import('./src/components/course/TheCourseCreationForm.vue')['default']
    TheCourseUseLine: typeof import('./src/components/statistics/TheCourseUseLine.vue')['default']
    TheDeviceListCard: typeof import('./src/components/personal/security/TheDeviceListCard.vue')['default']
    TheEmailModifyCard: typeof import('./src/components/personal/info/TheEmailModifyCard.vue')['default']
    TheGroupLearningDurationBar: typeof import('./src/components/statistics/TheGroupLearningDurationBar.vue')['default']
    TheGroupLearningTimeBar: typeof import('./src/components/statistics/TheGroupLearningTimeBar.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInstallAppCard: typeof import('./src/components/personal/about/TheInstallAppCard.vue')['default']
    TheLogoutCard: typeof import('./src/components/personal/security/TheLogoutCard.vue')['default']
    TheP5Banner: typeof import('./src/components/TheP5Banner.vue')['default']
    ThePasswordModifyCard: typeof import('./src/components/personal/security/ThePasswordModifyCard.vue')['default']
    TheRecentContainerTable: typeof import('./src/components/statistics/TheRecentContainerTable.vue')['default']
    TheStuCourseFinishedBarChart: typeof import('./src/components/statistics/TheStuCourseFinishedBarChart.vue')['default']
    TheUserBasicInfoCard: typeof import('./src/components/personal/info/TheUserBasicInfoCard.vue')['default']
  }
}
