/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomAttachmentCard: typeof import('./src/components/CustomAttachmentCard.vue')['default']
    CustomCourseCard: typeof import('./src/components/course/CustomCourseCard.vue')['default']
    CustomCourseStructureList: typeof import('./src/components/course/CustomCourseStructureList.vue')['default']
    CustomDeviceCard: typeof import('./src/components/CustomDeviceCard.vue')['default']
    CustomFloatBackButton: typeof import('./src/components/CustomFloatBackButton.vue')['default']
    CustomHorizontalCourseCard: typeof import('./src/components/CustomHorizontalCourseCard.vue')['default']
    CustomMessageCard: typeof import('./src/components/CustomMessageCard.vue')['default']
    CustomPluginCard: typeof import('./src/components/plugin/CustomPluginCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticEntryCard: typeof import('./src/components/personal/statistic/StatisticEntryCard.vue')['default']
    TheAccountBindCard: typeof import('./src/components/personal/info/TheAccountBindCard.vue')['default']
    TheAvatarModifyCard: typeof import('./src/components/personal/info/TheAvatarModifyCard.vue')['default']
    TheCourseContentModifyCard: typeof import('./src/components/course/TheCourseContentModifyCard.vue')['default']
    TheCourseCreationForm: typeof import('./src/components/course/TheCourseCreationForm.vue')['default']
    TheDeviceListCard: typeof import('./src/components/personal/security/TheDeviceListCard.vue')['default']
    TheEmailModifyCard: typeof import('./src/components/personal/info/TheEmailModifyCard.vue')['default']
    TheFormDataContent: typeof import('./src/components/plugin/backend/body/TheFormDataContent.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInstallAppCard: typeof import('./src/components/personal/about/TheInstallAppCard.vue')['default']
    TheJsonContent: typeof import('./src/components/plugin/backend/body/TheJsonContent.vue')['default']
    TheLogoutCard: typeof import('./src/components/personal/security/TheLogoutCard.vue')['default']
    TheMessageListCard: typeof import('./src/components/home/TheMessageListCard.vue')['default']
    TheP5Banner: typeof import('./src/components/TheP5Banner.vue')['default']
    ThePasswordModifyCard: typeof import('./src/components/personal/security/ThePasswordModifyCard.vue')['default']
    ThePluginListCard: typeof import('./src/components/home/ThePluginListCard.vue')['default']
    TheRequestBodyContent: typeof import('./src/components/plugin/backend/request/TheRequestBodyContent.vue')['default']
    TheRequestContent: typeof import('./src/components/plugin/backend/TheRequestContent.vue')['default']
    TheRequestHeaderContent: typeof import('./src/components/plugin/backend/request/TheRequestHeaderContent.vue')['default']
    TheRequestNoneBodyContent: typeof import('./src/components/plugin/backend/body/TheRequestNoneBodyContent.vue')['default']
    TheRequestParamContent: typeof import('./src/components/plugin/backend/request/TheRequestParamContent.vue')['default']
    TheRequestResult: typeof import('./src/components/plugin/backend/TheRequestResult.vue')['default']
    TheResponseHeaderContent: typeof import('./src/components/plugin/backend/response/TheResponseHeaderContent.vue')['default']
    TheResponseJsonContent: typeof import('./src/components/plugin/backend/response/TheResponseJsonContent.vue')['default']
    TheResponseRawContent: typeof import('./src/components/plugin/backend/response/TheResponseRawContent.vue')['default']
    TheUserBasicInfoCard: typeof import('./src/components/personal/info/TheUserBasicInfoCard.vue')['default']
  }
}
