/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomAttachmentCard: typeof import('./src/components/CustomAttachmentCard.vue')['default']
    CustomCourseCard: typeof import('./src/components/course/CustomCourseCard.vue')['default']
    CustomCourseList: typeof import('./src/components/course/CustomCourseList.vue')['default']
    CustomCourseStructureList: typeof import('./src/components/course/CustomCourseStructureList.vue')['default']
    CustomCourseTaskList: typeof import('./src/components/course/CustomCourseTaskList.vue')['default']
    CustomDeviceCard: typeof import('./src/components/CustomDeviceCard.vue')['default']
    CustomFloatBackButton: typeof import('./src/components/CustomFloatBackButton.vue')['default']
    CustomHorizontalCourseCard: typeof import('./src/components/CustomHorizontalCourseCard.vue')['default']
    CustomMessageCard: typeof import('./src/components/CustomMessageCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticEntryCard: typeof import('./src/components/personal/statistic/StatisticEntryCard.vue')['default']
    TheAccountBindCard: typeof import('./src/components/personal/info/TheAccountBindCard.vue')['default']
    TheAvatarModifyCard: typeof import('./src/components/personal/info/TheAvatarModifyCard.vue')['default']
    TheCourseContentModifyCard: typeof import('./src/components/course/TheCourseContentModifyCard.vue')['default']
    TheCourseCountBar: typeof import('./src/components/statistics/TheCourseCountBar.vue')['default']
    TheCourseCountBarChart: typeof import('./src/components/statistics/TheCourseCountBarChart.vue')['default']
    TheCourseCountByDateChart: typeof import('./src/components/statistics/TheCourseCountByDateChart.vue')['default']
    TheCourseCountChart: typeof import('./src/components/statistics/TheCourseCountChart.vue')['default']
    TheCourseCountLineChart: typeof import('./src/components/statistics/TheCourseCountLineChart.vue')['default']
    TheCourseCountPieChart: typeof import('./src/components/statistics/TheCourseCountPieChart.vue')['default']
    TheCourseCreationForm: typeof import('./src/components/course/TheCourseCreationForm.vue')['default']
    TheCourseModifyCard: typeof import('./src/components/course/TheCourseModifyCard.vue')['default']
    TheCourseStructureCard: typeof import('./src/components/course/TheCourseStructureCard.vue')['default']
    TheDeviceListCard: typeof import('./src/components/personal/security/TheDeviceListCard.vue')['default']
    TheEmailModifyCard: typeof import('./src/components/personal/info/TheEmailModifyCard.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLogoutCard: typeof import('./src/components/personal/security/TheLogoutCard.vue')['default']
    TheP5Banner: typeof import('./src/components/TheP5Banner.vue')['default']
    ThePasswordModifyCard: typeof import('./src/components/personal/security/ThePasswordModifyCard.vue')['default']
    TheSectionCreationForm: typeof import('./src/views/teacher/course/SectionCreationForm.vue')['default']
    TheTaskCreationForm: typeof import('./src/views/teacher/course/TheTaskCreationForm.vue')['default']
    TheUserBasicInfoCard: typeof import('./src/components/personal/info/TheUserBasicInfoCard.vue')['default']
  }
}
